name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Lint code
      run: |
        pnpm --filter api lint
        pnpm --filter web lint

    - name: Type check
      run: |
        pnpm --filter api typecheck
        pnpm --filter web typecheck
        pnpm --filter switchbot-adapter tsc --noEmit
        pnpm --filter shared tsc --noEmit
        pnpm --filter harmony-tools tsc --noEmit

    - name: Run tests
      run: |
        pnpm --filter switchbot-adapter test
        pnpm --filter api test
        pnpm --filter web test

    - name: Build applications
      run: |
        pnpm --filter api build
        pnpm --filter web build

    - name: Upload test coverage
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x'
      with:
        fail_ci_if_error: false

  security-scan:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run security audit
      run: pnpm audit --audit-level high

    - name: Check for known vulnerabilities
      run: |
        pnpm --filter api audit
        pnpm --filter web audit
        pnpm --filter switchbot-adapter audit


